// Supplementary catalogue: probe landing sites + colloquial (informal) feature
// names, generated by scripts/build_supplementary.py into supplementary.json.
// Loaded non-fatally — the app degrades to the official catalogue without it.

import { asset } from "../lib/meta";
import type { Alias, MarsFeature } from "./types";

export interface LandingSite {
  id: number;        // 9_000_000 + landing_id — stable, safe to persist (study store)
  landingId: number;
  name: string;      // short display label, e.g. "Perseverance"
  mission: string;
  craft: string;
  agency: string;
  country: string;
  launchDate: string;  // ISO date
  landingDate: string; // ISO date
  region: string;
  memorialName: string; // "" when none
  lat: number;
  lon180: number;
  lonEast360: number;
  success: boolean;
  outcome: string;
  notes: string;
  source: string;
}

export interface ColloquialFeature {
  id: number; // 9_100_000 + build index — BUILD-LOCAL, must never be persisted
  name: string;
  className: string;  // e.g. "Hill, butte, mesa"
  classShort: string; // e.g. "hill"
  region: string;     // host region text, e.g. "Gale crater"
  lat: number;
  lon180: number;
  lonEast360: number;
  sizeKm: number | null;
  year: number | null;
  description: string;
  hostLandingId: number | null; // nearest landing site id within 1.5°
}

export interface Supplementary {
  aliases: Alias[];
  colloquial: ColloquialFeature[];
  landingSites: LandingSite[];
}

export const EMPTY_SUPPLEMENTARY: Supplementary = {
  aliases: [],
  colloquial: [],
  landingSites: [],
};

interface RawAlias {
  alias: string; official_id: number; official_name: string;
  year: number | null; description: string;
}
interface RawColloquial {
  id: number; name: string; class_name: string; class_short: string;
  region: string; lat: number; lon180: number; lon_east360: number;
  size_km: number | null; year: number | null; description: string;
  host_landing_id: number | null;
}
interface RawLanding {
  id: number; landing_id: number; name: string; mission: string; craft: string;
  agency: string; country: string; launch_date: string; landing_date: string;
  region: string; memorial_name: string; lat: number; lon180: number;
  lon_east360: number; success: boolean; outcome: string; notes: string;
  source: string;
}

export async function loadSupplementary(): Promise<Supplementary> {
  const res = await fetch(asset("data/supplementary/supplementary.json"), { cache: "no-cache" });
  if (!res.ok) throw new Error(`supplementary.json ${res.status}`);
  const raw = (await res.json()) as {
    aliases: RawAlias[]; colloquial: RawColloquial[]; landing_sites: RawLanding[];
  };
  return {
    aliases: raw.aliases.map((a) => ({
      alias: a.alias,
      officialId: a.official_id,
      officialName: a.official_name,
      year: a.year ?? null,
      description: a.description ?? "",
    })),
    colloquial: raw.colloquial.map((c) => ({
      id: c.id,
      name: c.name,
      className: c.class_name,
      classShort: c.class_short,
      region: c.region,
      lat: c.lat,
      lon180: c.lon180,
      lonEast360: c.lon_east360,
      sizeKm: c.size_km ?? null,
      year: c.year ?? null,
      description: c.description ?? "",
      hostLandingId: c.host_landing_id ?? null,
    })),
    landingSites: raw.landing_sites.map((s) => ({
      id: s.id,
      landingId: s.landing_id,
      name: s.name,
      mission: s.mission,
      craft: s.craft,
      agency: s.agency,
      country: s.country,
      launchDate: s.launch_date,
      landingDate: s.landing_date,
      region: s.region,
      memorialName: s.memorial_name ?? "",
      lat: s.lat,
      lon180: s.lon180,
      lonEast360: s.lon_east360,
      success: s.success,
      outcome: s.outcome,
      notes: s.notes ?? "",
      source: s.source ?? "",
    })),
  };
}

/** Attach each alias to its official feature (f.aka), preserving alias order. */
export function applyAliases(features: MarsFeature[], aliases: Alias[]): void {
  if (aliases.length === 0) return;
  const byId = new Map(features.map((f) => [f.id, f]));
  for (const a of aliases) {
    const f = byId.get(a.officialId);
    if (f) (f.aka ??= []).push(a);
  }
}

/** Colloquial features grouped by their host landing-site id, sorted by name. */
export function nearbyBySite(colloquial: ColloquialFeature[]): Map<number, ColloquialFeature[]> {
  const map = new Map<number, ColloquialFeature[]>();
  for (const c of colloquial) {
    if (c.hostLandingId == null) continue;
    const list = map.get(c.hostLandingId);
    if (list) list.push(c);
    else map.set(c.hostLandingId, [c]);
  }
  return map; // converter emits colloquial sorted by name, so groups stay sorted
}
